CREATE TABLE ROLES (
  ID VARCHAR(20) NOT NULL PRIMARY KEY UNIQUE
);

CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USER VARCHAR(100) NOT NULL UNIQUE ,
  USER_NAME VARCHAR(60) UNIQUE ,
  RATING INT NOT NULL DEFAULT '0',
  ID_ROLE VARCHAR(20) NOT NULL DEFAULT 'User',
  DATA_CHECK_IN DATETIME NOT NULL DEFAULT now(),
  DATA_LAST_CHECK_IN DATETIME NOT NULL DEFAULT now(),
  FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID)
);

CREATE TABLE CATEGORIES (
  ID VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TAGS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(60) UNIQUE NOT NULL
);

CREATE TABLE RECIPE (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(70),
  ID_USER INT NOT NULL,
  ID_CATEGORY VARCHAR(100) NOT NULL,
  VIDEO TEXT DEFAULT NULL,
  FULLTEXT (NAME),
  FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
  FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES(ID)
);

CREATE TABLE STEPS (
  ID INT NOT NULL AUTO_INCREMENT,
  STEP_NUMBER INT NOT NULL,
  ID_RECIPE INT NOT NULL,
  IMAGE_LINK VARCHAR(255),
  NAME VARCHAR(100) NOT NULL,
  BODY MEDIUMTEXT,
  FULLTEXT (BODY, NAME),
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_RECIPE) REFERENCES RECIPE(ID) ON DELETE CASCADE
);

CREATE TABLE COMMENTS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  ID_STEP INT NOT NULL,
  ID_USER INT NOT NULL ,
  BODY TEXT NOT NULL,
  FULLTEXT (BODY),
  FOREIGN KEY (ID_STEP) REFERENCES STEPS(ID),
  FOREIGN KEY (ID_USER) REFERENCES USERS(ID)
);

CREATE TABLE RATING (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  ID_RECIPE INT NOT NULL ,
  ID_USER INT NOT NULL,
  MARK INT(1) NOT NULL,
  FOREIGN KEY (ID_RECIPE) REFERENCES RECIPE(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_USER) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE RECIPE_TAGS (
  ID_RECIPE INT NOT NULL,
  ID_TAGS INT NOT NULL,
  FOREIGN KEY (ID_RECIPE) REFERENCES RECIPE(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_TAGS) REFERENCES TAGS(ID),
  PRIMARY KEY (ID_RECIPE, ID_TAGS)
);

SELECT * FROM USERS u LEFT JOIN RECIPE r ON u.id=r.ID_USER LEFT JOIN STEPS s
  ON s.ID_RECIPE=r.ID LEFT JOIN COMMENTS c on c.ID_STEP=s.ID;